### ISSUE TITLE
API key present in the code

### ISSUE THREAD

**Issue by JohnnySheffield** [sirius2013/HandPointPlugin#1]
Not sure is it just a test API key, but in the file https://github.com/sirius2013/HandPointPlugin/blob/master/example/js/index.js there is an Merchant API key present.

If this is not sensitive info - please disregard and close.

Cheers!

**Comment by cquezpro** [comment]
hi

**Comment by JohnnySheffield** [comment]
Hi @sirius2013 

Just noticed this API key is the same as on the Handpint webpage here https://www.handpoint.com/docs/basics/dev-kit-and-simulator

so closing this issue - as it is public info obviously! :stuck_out_tongue_closed_eyes:
