### ISSUE TITLE
Getting this plugin to work - bounty for assistance

### ISSUE THREAD

**Issue by chris-jamieson** [sirius2013/HandPointPlugin#2]
Hi! Firstly thank you for taking the time to write and publish this Cordova plugin for the Handpoint library.

I've been working with it for a few days and I am struggling to get the plugin to run (even the example you provided seems to throw some errors, which may well be my fault).

I realise you developed this a couple of years ago, but I wanted you contact you because I'm working on a project that would be great to make use of your plugin, and I have a budget to offer if you could help to get it working. Please contact me on Github (here) or on hi@chrisjamieson.me - I would love to chat and potentially work with you if that's of interest.

Thanks in advance! Chris

**Comment by cquezpro** [comment]
Hi!
